services:
  bimrocket-webapp:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: bimrocket-webapp
    container_name: bimrocket-webapp
    restart: always
    environment:
      - BIMROCKET_ENV=/root/bimrocket/js/Environment.js
    ports:
      - "8181:8080"
    volumes:
      - ../target/bimrocket.war:/usr/local/tomcat/webapps/bimrocket.war
    networks:
      - bimrocket_network

networks:
  bimrocket_network:
    driver: bridge